# How to Run 
# ansible-playbook deployment.yml
# Process in detail: https://confluence.slac.stanford.edu/display/LCLSControls/CD+-+Deployment+Stage

# Deploys all components needed for build system at production k8s cluster 'ad-build'

# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html#ansible-collections-kubernetes-core-k8s-module
- name: Build System Deployment
  hosts: localhost
  vars:
    k8s_namespace: 'core-build-system'
  tasks:
# TODO:
# 0) ansible-galaxy collection install kubernetes.core
# 0) Authenticate to the cluster - it automatically gets the credentials/config of localhost machine

# 1) Create namespace
  - name: Create a core-build-system namespace
    kubernetes.core.k8s:
      name: core-build-system
      api_version: v1
      kind: Namespace
      state: present
# 2) create a temporary directory, git clone all pieces needed (mongodb, core-build-system-deployment, BuildSystem)
  - name: Create temporary directory for deployment
    ansible.builtin.tempfile:
      state: directory
      suffix: temp_deployment
    register: temp_directory
  - name: Git checkout mongodb deployment
    ansible.builtin.git:
      repo: 'https://github.com/eed-web-application/eed-accel-webapp-clusters-wide-setup.git'
      dest: '{{ temp_directory.path }}/eed-accel-webapp-clusters-wide-setup'
      version: main
  - name: Git checkout core-build-system deployment
    ansible.builtin.git:
      repo: 'https://github.com/eed-web-application/core-build-system-deployment.git'
      dest: '{{ temp_directory.path }}/core-build-system-deployment'
      version: ad-build-dev
  - name: Git checkout BuildSystem deployment
    ansible.builtin.git:
      repo: 'https://github.com/ad-build-test/BuildSystem.git'
      dest: '{{ temp_directory.path }}/BuildSystem'
      version: main
# 3) core-build-system
  # 3.1) apply server side mongodb resources
  - name: Apply server side mongodb resources
    kubernetes.core.k8s:
      namespace: '{{ k8s_namespace }}'
      state: present
      src: '{{ temp_directory.path }}/eed-accel-webapp-clusters-wide-setup/prod/mongodb-operator/1.16.2/crd-1.16.2.yaml'
      apply: yes 
      server_side_apply: 
        field_manager: ansible
        force_conflicts: true
  # 3.2) apply core-build-system-deployment
  - name: Find all core-build-system-deployment YAML files
    ansible.builtin.find:
      paths: "{{ temp_directory.path }}/core-build-system-deployment/ad-build/"
      patterns: "*.yaml,*.yml"
      excludes: "kustomization.yaml"
    register: yaml_files
  - name: Apply core-build-system backend service
    kubernetes.core.k8s:
      namespace: '{{ k8s_namespace }}'
      state: present
      src: "{{ item.path }}"
      apply: yes 
    loop: "{{ yaml_files.files }}"
# 4) BuildSystem
  # 4.1) apply deployment controller
  - name: Find all deployment controller api YAML files
    ansible.builtin.find:
      paths: "{{ temp_directory.path }}/BuildSystem/deploy_controller/controller_deployment/"
      patterns: "*.yaml,*.yml"
      excludes: "kustomization*, *_dev.yaml"
    register: yaml_files
  - name: Apply deploymment controller api service
    kubernetes.core.k8s:
      namespace: '{{ k8s_namespace }}'
      state: present
      src: "{{ item.path }}"
      apply: yes 
    loop: "{{ yaml_files.files }}"

# 4) Inspect the cluster make sure everything looks good
  # 4.1) Run sample curl request to backend to see if its working