- hosts: all
  vars:
    facility: '{{ facility }}'
    component_name: '{{ component_name }}'
    tag: '{{ tag }}'
    user: '{{ user }}'
    tarball: '{{ tarball }}'

  tasks:
  - include_tasks: ../common/deploy_tasks.yml
    vars:
      release_folder: '{{ hla_release_folder }}'
      link_folder: '{{ hla_link_folder }}'
      link_name: '{{ component_name }}'
