# deployment location ($APP or $PHYSICS_TOP or $TOOLS/script or $PYDYM etc.)
# Process in detail: https://confluence.slac.stanford.edu/display/LCLSControls/CD+-+Deployment+Stage

- hosts: all
# All hosts are availble to use, but user can run this playbook on specific
# servers using '-l <facility>''
  vars: 
    facility: '{{ facility }}'
    component_name: '{{ component_name }}'
    tag: '{{ tag }}'
    user: '{{ user }}'
    tarball: '{{ tarball }}'
    subsystem: '{{ subsystem }}' # Name of subsystem like (mps, ntwk, mgnt, etc) How it shows up at $PYDM

  tasks:
  - include_tasks: ../common/deploy_tasks.yml
    vars:
      release_folder: '{{ pydm_release_folder }}'
      link_folder: '{{ pydm_link_folder }}'
      link_name: '{{ subsystem }}'


