
- name: Deploy app, and update envPaths
  hosts: all
  # All vars from ioc_deploy.yml are accessible
  gather_facts: no
  tasks:
  - name: Extract build results to '{{ ioc_release_folder }}/{{ component_name }}'
    ansible.builtin.unarchive:
      src: '{{ tarball }}'
      dest: '{{ ioc_release_folder }}/{{ component_name }}'

  - name: Update envPaths (call cram script for this) '{{ facility }}'
    ansible.builtin.shell: python3 library/env_paths_update.py {{ component_name }} SIOC {{ ioc_release_folder }} MASTER {{ tag }}
  # MASTER - i think its safe to assume you want all IOCs in a different facility
  # to update their envPaths to match, regardless if thats the one you deployed
  
  # If have time, make it ansible module for idempotency
  # - name: Update envPaths (call cram script for this) '{{ facility }}'
  #   # ansible.builtin.shell: python3 env_paths_update.py {{ app }}
  #   env_paths_update:
  #     deploy_type: 'IOC' 
  #   register: testout
  # - name: Dump envPaths update output
  #   debug:
  #     msg: '{{ testout }}'