# How to Run 
# ansible-playbook --extra-vars "user=$USER ioc_name=sioc-123-123 executable_path=/afs/slac.stanford.edu/u/cd/pnispero/mps/central_node_ioc/" ./initial_softioc_deploy.yml
# This is for dev, and doesn't include using 'cram' and deploying a component to a 
# deployment location ($APP or $PHYSICS_TOP or $TOOLS/script or $PYDYM etc.)
# Process in detail: https://confluence.slac.stanford.edu/display/LCLSControls/CD+-+Deployment+Stage
- name: Initial IOC Deployment
  hosts: all
  # All vars from ioc_deploy.yml are accessible in addition to these:
  vars:
    data_directories:
      - 'archive'
      - 'autosave'
      - 'autosave-req'
      - 'iocInfo'
      - 'restore'
      - 'yaml'
  gather_facts: no
  tasks:
  # Each directory creation will have a task to check first if directory already exists, if not then create it
  # Added a check first because if already exists and the permissions don't match here, then the task will fail.
  - name: 'Check if component directory exists at $APP {{ ioc_release_folder }}/{{ component_name }}'
    ansible.builtin.stat:
      path: '{{ ioc_release_folder }}/{{ component_name }}'
    register: dir_stat

  - name: 'Create component directory at $APP {{ ioc_release_folder }}/{{ component_name }}'
    ansible.builtin.file:
      path: '{{ ioc_release_folder }}/{{ component_name }}'
      state: directory
      mode: '775' # drwxrwxr-x
    when: not dir_stat.stat.exists

  - name: 'Check if ioc directories exist at $IOC {{ ioc_link_folder }}/<ioc>'
    ansible.builtin.stat:
      path: '{{ ioc_link_folder }}/{{ item.name }}'
    loop: "{{ ioc_list }}"
    loop_control:
      label: '{{ ioc_link_folder }} - {{ item.name }}'
    register: dir_stats

  - name: 'Create ioc directory at $IOC {{ ioc_link_folder }}/<ioc>'
    ansible.builtin.file:
      path: '{{ ioc_link_folder }}/{{ dir_check.item.name }}'
      state: directory
      mode: '775' # drwxrwxr-x
    loop: "{{ dir_stats.results }}"
    loop_control:
      label: '{{ ioc_link_folder }} - {{ dir_check.item.name }}'
      loop_var: dir_check
    when: not dir_check.stat.exists

  - name: 'Create sym link at $IOC {{ ioc_link_folder }}/<ioc>/iocSpecificRelease to point to {{ ioc_release_folder }}/{{ component_name }}/<tag>'
    ansible.builtin.file:
      src: '{{ ioc_release_folder }}/{{ component_name }}/{{ tag }}'
      dest: '{{ ioc_link_folder }}/{{ item.name }}/iocSpecificRelease'
      state: link
      force: true # Force creation even if src dir doesn't exist since it won't if this is initial deployment
    loop: "{{ ioc_list }}"
    loop_control:
      label: '{{ ioc_link_folder }}/{{ item.name }}/iocSpecificRelease -> {{ ioc_release_folder }}/{{ component_name }}/{{ tag }}'

  - name: 'Check if ioc directories exist at $IOC_DATA {{ ioc_data_folder }}/<ioc>'
    ansible.builtin.stat:
      path: '{{ ioc_data_folder }}/{{ item.name }}'
    loop: "{{ ioc_list }}"
    loop_control:
      label: '{{ ioc_data_folder }} - {{ item.name }}'
    register: dir_stats

  - name: 'Create ioc directory at $IOC_DATA {{ ioc_data_folder }}/<ioc>'
    ansible.builtin.file:
      path: '{{ ioc_data_folder }}/{{ dir_check.item.name }}'
      state: directory
      mode: '775' # drwxrwxr-x
    loop: "{{ dir_stats.results }}"
    loop_control:
      label: '{{ ioc_data_folder }} - {{ dir_check.item.name }}'
      loop_var: dir_check
    when: not dir_check.stat.exists

  - name: Check if data directories exist at $IOC_DATA {{ ioc_data_folder }}/<ioc>
    ansible.builtin.stat:
      path: "{{ ioc_data_folder }}/{{ item.0.name }}/{{ item.1 }}"
    loop: "{{ (ioc_list | list) | product(data_directories) | list }}"
    loop_control:
      label: "{{ ioc_data_folder }}/{{ item.0.name }} - {{ item.1 }}"
    register: dir_stats

  - name: Create multiple data directories at $IOC_DATA {{ ioc_data_folder }}/<ioc>
    ansible.builtin.file:
      path: "{{ dir_check.item.0.name }}/{{ dir_check.item.1 }}"
      state: directory
      mode: '775'
    loop: "{{ dir_stats.results }}"
    loop_control:
      label: "{{ ioc_data_folder }}/{{ dir_check.item.0.name }} - {{ dir_check.item.1 }}"
      loop_var: dir_check
    when: not dir_check.stat.exists

# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_templating.html

  - name: 'Add startup.cmd/st.cmd for the IOC at {{ ioc_link_folder }}/<ioc>'
    ansible.builtin.template:
      src: "./templates/{{ item.startup_cmd_template }}"  # Path to your template in the 'templates' directory
      dest: "{{ ioc_link_folder }}/{{ item.name }}/startup.cmd"  # Destination path where the final file will be saved
      mode: '0775'  # You can set the appropriate file permissions
    loop: "{{ ioc_list }}"
    vars:
      exe: "{{ item.binary }}"  # Pass the 'binary' value from the IOC dictionary as the 'exe' variable to the template
      t_a: "{{ item.architecture }}"  # Pass the 'architecture' value from the IOC dictionary to the template
      ioc: "{{ item.name }}" # Pass the 'name' value form the IOC dictionary as the 'ioc'
      cpu: "{{ item.name }}" # Pass the 'name' value form the IOC dictionary as the 'cpu'