# How to Run 
# ansible-playbook --extra-vars "user=$USER ioc_name=sioc-123-123 executable_path=/afs/slac.stanford.edu/u/cd/pnispero/mps/central_node_ioc/" ./initial_softioc_deploy.yml
# This is for dev, and doesn't include using 'cram' and deploying a component to a 
# deployment location ($APP or $PHYSICS_TOP or $TOOLS/script or $PYDYM etc.)
# Process in detail: https://confluence.slac.stanford.edu/display/LCLSControls/CD+-+Deployment+Stage
- name: Initial IOC Deployment
  hosts: all
  # All vars from ioc_deploy.yml are accessible in addition to these:
  vars:
    data_directories:
      - 'archive'
      - 'autosave'
      - 'autosave-req'
      - 'iocInfo'
      - 'restore'
      - 'yaml'
  gather_facts: no
  tasks:
  - name: 'Create component directory at {{ ioc_release_folder }}/{{ component_name }}'
    ansible.builtin.file:
      path: '{{ ioc_release_folder }}/{{ component_name }}'
      state: directory
      mode: '775' # drwxrwxr-x

  - name: 'Create ioc directory at $IOC {{ ioc_link_folder }}/<ioc>'
    ansible.builtin.file:
      path: '{{ ioc_link_folder }}/{{ item }}'
      state: directory
      mode: '775' # drwxrwxr-x
    loop: "{{ ioc_list }}"
    loop_control:
      label: '{{ ioc_link_folder }} - {{ item }}'

  - name: 'Create sym link {{ ioc_link_folder }}/<ioc>/iocSpecificRelease to point to {{ ioc_release_folder }}/{{ component_name }}/<tag>'
    ansible.builtin.file:
      src: '{{ ioc_release_folder }}/{{ component_name }}/{{ tag }}'
      dest: '{{ ioc_link_folder }}/{{ item }}/iocSpecificRelease'
      state: link
      force: true # Force creation even if src dir doesn't exist since it won't if this is initial deployment
    loop: "{{ ioc_list }}"
    loop_control:
      label: '{{ ioc_link_folder }}/{{ item }}/iocSpecificRelease -> {{ ioc_release_folder }}/{{ component_name }}/{{ tag }}'

    # 1) In $IOC_DATA, make directory for ioc if doesn't already exist
  - name: 'Create ioc directory in {{ ioc_data_folder }}/<ioc>'
    ansible.builtin.file:
      path: '{{ ioc_data_folder }}/{{ item }}'
      state: directory
      mode: '775' # drwxrwxr-x
    loop: "{{ ioc_list }}"
    loop_control:
      label: '{{ ioc_data_folder }} - {{ item }}'

  - name: Create multiple data directories in {{ ioc_data_folder }}/<ioc>
    ansible.builtin.file:
      path: "{{ ioc_data_folder }}/{{ item.0 }}/{{ item.1 }}"
      state: directory
      mode: '775'
    loop: "{{ (ioc_list | list) | product(data_directories) | list }}"
    loop_control:
      label: "{{ ioc_data_folder }}/{{ item.0 }} - {{ item.1 }}"

  # TODO:
  - name: 'Add startup.cmd/st.cmd for the IOC at {{ ioc_link_folder }}/<ioc>'
    block:
    - name: 'Add startup.cmd/st.cmd for the IOC at {{ ioc_link_folder }}/<ioc>'
      ansible.builtin.fail:
        msg: == ADBS == UNFINSHED. Please do this step manually.
      loop: "{{ ioc_list }}"
      loop_control:
        label: '== ADBS == {{ item }}'
    rescue:
    - name: == ADBS == Continue despite previous error
      ansible.builtin.debug:
        msg: Startup.cmd automation is unfinished, please create the startup.cmd manually.

  # TODO: this task (although may not be worth doing if theres too much variation)
  # - name: Create startup.cmd (dev) st.cmd (prod)

  # - name: Start ioc and shell into it
  #   ansible.builtin.shell: xterm -hold -e "siocRestart '{{ ioc_name }}' && iocConsole '{{ ioc_name }}'"


