# How to Run 
# ansible-playbook -i local_inventory --extra-vars "initial=true user=$USER iocCommon=$IOC iocData=$IOC_DATA ioc_name=sioc-123-123 executable_path=/afs/slac.stanford.edu/u/cd/pnispero/mps/central_node_ioc/" ./ioc_deploy.yml
# This is for dev, and doesn't include using 'cram' and deploying a component to a 
# deployment location ($APP or $PHYSICS_TOP or $TOOLS/script or $PYDYM etc.)
# Process in detail: https://confluence.slac.stanford.edu/display/LCLSControls/CD+-+Deployment+Stage
# This is a 'master playbook' that would call other ioc playbooks based off
# what is needed, mainly initial / normal deployment

- hosts: all
# All hosts are availble to use, but user can run this playbook on specific
# servers using '-l <facility>''
  vars: 
    initial: '{{ initial }}' # From CLI
    facility: '{{ facility }}' # From CLI
    user_src_repo: '{{ user_src_repo }}' # From CLI
    component_name: '{{ component_name }}' # From CLI
    tag: '{{ tag }}' # From CLI
    user: '{{ user }}' # From CLI
    ioc_list: '{{ ioc_list }}' # From CLI
    tarball: '{{ tarball }}' # From CLI - full filepath to build results tarball

  # Instead of tasks, just call the other 'regular' ioc deployment playbook
  # Removed gathering_facts for other playbooks since already done in this main one
- name: 'Initial ioc deployment - {{ facility }}' # This playbook is usually only ran once when an ioc is deployed for the first time
  ansible.builtin.import_playbook: initial_ioc_deploy.yml
  when: initial | bool

- name: 'IOCs app deployment - {{ facility }}' # This playbook is always called
  ansible.builtin.import_playbook: app_deploy.yml

- name: 'Normal ioc deployment - {{ facility }}' # This playbook is always called
  ansible.builtin.import_playbook: normal_ioc_deploy.yml


