# Process in detail: https://confluence.slac.stanford.edu/display/LCLSControls/CD+-+Deployment+Stage

- name: IOC package build
  hosts: localhost
  gather_facts: no
  vars:
    component: '{{ component }}'
    branch: '{{ branch }}'
    user_src_repo: '{{ user_src_repo }}'
    build_results: '{{ user_src_repo }}/build_results'

  tasks:
  - name: 'Create build_results/{{ component }}-{{ branch }} directory'
    ansible.builtin.file:
      path: '{{ build_results }}/{{ component }}-{{ branch }}'
      state: directory
      mode: '775' # drwxrwxr-x

  - name: 'Push bin/ db/ dbd/ iocBoot/ to build_results/{{ component }}-{{ branch }} directory'
    ansible.posix.synchronize:
      src: '{{ item }}'
      dest: '{{ build_results }}/{{ component }}-{{ branch }}'
      mode: push
    loop:
      - '{{ user_src_repo }}/bin'
      - '{{ user_src_repo }}/db'
      - '{{ user_src_repo }}/dbd'
      - '{{ user_src_repo }}/iocBoot'
      - '{{ user_src_repo }}/build.log'
    ignore_errors: yes # In place in case build.log is missing for local builds
    # no '/' on directories, otherwise it won't copy the directory itself just the contents

  - name: Package app with tarball
    ansible.builtin.shell: tar czf {{ build_results }}/{{ component }}-{{ branch }}.tar.gz -C {{ build_results}} {{ component }}-{{ branch }}

