# How to Run 
# This playbook is called by the software factory (build system) deployment controller
# Process in detail: https://confluence.slac.stanford.edu/display/LCLSControls/CD+-+Deployment+Stage
# This is a 'master playbook' that would call other ioc playbooks

- hosts: all
# All hosts are availble to use, but user can run this playbook on specific
# servers using '-l <facility>''
  environment:
    EPICS_TOP: "{{ epics_top }}"
    EPICS_BASE_TOP: "{{ epics_base_top }}"
    PACKAGE_TOP: "{{ package_top }}"
    TOOLS: "{{ tools }}"
  vars: 
    reboot_iocs: '{{ reboot_iocs }}'
    facility: '{{ facility }}'
    user_src_repo: '{{ user_src_repo }}'
    component_name: '{{ component_name }}'
    tag: '{{ tag }}'
    user: '{{ user }}'
    ioc_list: '{{ ioc_list }}'
    # ioc_list Structure:
    # [
    #     {
    #         "architecture": "rhel6-x86_64",
    #         "binary": "oscilloscope",
    #         "name": "sioc-b34-sc01",
    #         "startup_cmd_template": "startup.cmd.soft"
    #     },
    #     {
    #         "architecture": "rhel6-x86_64",
    #         "binary": "oscilloscope",
    #         "name": "sioc-b34-sc02",
    #         "startup_cmd_template": "startup.cmd.soft"
    #     }
    # ]
    tarball: '{{ tarball }}' # full filepath to build results tarball
    playbook_path: '{{ playbook_path }}'

  # Instead of tasks, just call the other 'regular' ioc deployment playbook
  # Removed gathering_facts for other playbooks since already done in this main one
- name: 'Initial ioc deployment - {{ facility }}'
  ansible.builtin.import_playbook: initial_ioc_deploy.yml

- name: 'IOCs app deployment - {{ facility }}'
  ansible.builtin.import_playbook: app_deploy.yml

- name: 'Reboot iocs - {{ facility }}'
  ansible.builtin.import_playbook: reboot_iocs.yml


