- name: Normal IOC Deployment
  hosts: all
  # All vars from ioc_deploy.yml are accessible
  gather_facts: no
  tasks:

  - name: Find siocRestart command
    ansible.builtin.shell: which siocRestart
    register: sioc_restart_path
    when: reboot_iocs == true

  - name: Reboot IOC using siocRestart
    ansible.builtin.shell: "{{ sioc_restart_path.stdout }} {{ item.name }}"
    loop: "{{ ioc_list }}"
    loop_control:
      label: 'siocRestart {{ item.name }}'
    when: reboot_iocs == true
    register: restart_result
    ignore_errors: yes

  - name: Fail if any IOC restart failed
    fail:
      msg: "IOC restart failed for {{ item.item.name }}: {{ item.stdout | default(item.stderr) }}"
    loop: "{{ restart_result.results }}"
    when: 
      - restart_result.results is defined
      - item.failed | default(false)
    