
- name: test env paths parser
  hosts: localhost
  # All vars from ioc_deploy.yml are accessible
  vars:
    facility: S3DF
    app_name: test-ioc
    app_type: SIOC
    release_folder: /sdf/group/ad/eed/lcls/epics/iocTop
    ioc_name: MASTER
    # ioc_name - i think its safe to assume you want all IOCs in a different facility
    # to update their envPaths to match, regardless if thats the one you deployed, itll be there
    release_tag: test-ioc-1.0.0

  tasks:
  - name: Update envPaths (call cram script for this) '{{ facility }}'
    ansible.builtin.shell: python3 library/env_paths_update.py {{ app_name }} {{ app_type }} {{ release_folder }} {{ ioc_name }} {{ release_tag }}

  # - shell: echo $ANSIBLE_LIBRARY
  #   register: ANSIBLE_LIBRARY
  # - debug:
  #     msg: "ANSIBLE_LIBRARY is: {{ ANSIBLE_LIBRARY.stdout }}"
  # # TODO: Add ioc type because is needed for envPaths
  # # make it ansible module for idempotency
  # - name: Update envPaths (call cram script for this) '{{ facility }}'
  #   # ansible.builtin.shell: python3 env_paths_update.py {{ app }}
  #   env_paths_update:
  #     app_name: 'IOC'
  #     app_type: 'IOC' 
  #   register: testout
  # - name: Dump envPaths update output
  #   debug:
  #     msg: '{{ testout }}'